palette = "MyBlues"
format = """
[](color_blue_0)\
$os\
$username\
[](bg:color_blue_1 fg:color_blue_0)\
$directory\
[](fg:color_blue_1 bg:color_blue_2)\
$git_branch\
$git_status\
[](fg:color_blue_2 bg:color_blue_3)\
$python\
$nodejs\
$docker_context\
[](fg:color_blue_3 bg:color_blue_4)\
$time\
[ ](fg:color_blue_4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_blue_0"
style_root = "bg:color_blue_0"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:color_blue_0"
disabled = true # Disabled by default
format = ''

[directory]
style = "bg:color_blue_1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:color_blue_2"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_blue_2"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue_3"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:color_blue_3"
format = '[ $symbol $context ]($style) $path'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_blue_4 fg:color_blue_0"
format = '[  $time ]($style)'

[palettes.MyBlues]
color_blue_0 = "#0E1A29"
color_blue_1 = "#172C44"
color_blue_2 = "#325E91"
color_blue_3 = "#5F90C8"
color_blue_4 = "#BED2E9"
